###
# (C) Copyright (2012-2017) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- name:  set all master nodes scheduable
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  ignore_errors: true

- name: calico scale to all master nodes
  shell: kubectl scale --replicas=3 -n kube-system deployment/calico-kube-controllers
- pause: seconds=5

- name: scale up kube-dns replicas to 3, make all master running kube-dns
  shell: kubectl scale --replicas=3 -n kube-system deployment/kube-dns
- pause: seconds=5

- name: scale up kubernetes-dashboard replicas to 3, make all master running kubernetes-dashboard
  shell: kubectl scale --replicas=3 -n kube-system deployment/kubernetes-dashboard
- pause: seconds=5

