###
# (C) Copyright (2012-2017) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- name: remove existing etcd containers
  docker_container:
    name: etcd
    state: absent
  ignore_errors: true

- name: delete /var/lib/etcd-cluster directory.
  file: path=/var/lib/etcd-cluster state=absent

- name: create /var/lib/etcd-cluster directory.
  file: path=/var/lib/etcd-cluster state=directory

- name: start docker etcd container on master-1
  docker_container:
    name: etcd
    image: gcr.io/google_containers/etcd-amd64:3.0.17
    volumes:
    - '/etc/ssl/certs:/etc/ssl/certs'
    - '/var/lib/etcd-cluster:/var/lib/etcd'
    ports:
    - '4001:4001'
    - '2380:2380'
    - '2379:2379'
    restart_policy: always
    command:
      - etcd
      - --name=etcd0
      - --advertise-client-urls=http://{{ master1_ip }}:2379,http://{{ master1_ip }}:4001
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --initial-advertise-peer-urls=http://{{ master1_ip }}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster-token={{ ETCD_CLUSTER_TOKEN }}
      - --initial-cluster=etcd0=http://{{ master1_ip }}:2380,etcd1=http://{{ master2_ip }}:2380,etcd2=http://{{ master3_ip }}:2380
      - --initial-cluster-state=new
      - --auto-tls
      - --peer-auto-tls
      - --data-dir=/var/lib/etcd

  when: inventory_hostname in groups['master-1']

- name: start docker etcd container on master-2
  docker_container:
    name: etcd
    image: gcr.io/google_containers/etcd-amd64:3.0.17
    volumes:
    - '/etc/ssl/certs:/etc/ssl/certs'
    - '/var/lib/etcd-cluster:/var/lib/etcd'
    ports:
    - '4001:4001'
    - '2380:2380'
    - '2379:2379'
    restart_policy: always
    command:
      - etcd
      - --name=etcd1
      - --advertise-client-urls=http://{{ master2_ip }}:2379,http://{{ master2_ip }}:4001
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --initial-advertise-peer-urls=http://{{ master2_ip }}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster-token={{ ETCD_CLUSTER_TOKEN }}
      - --initial-cluster=etcd0=http://{{ master1_ip }}:2380,etcd1=http://{{ master2_ip }}:2380,etcd2=http://{{ master3_ip }}:2380
      - --initial-cluster-state=new
      - --auto-tls
      - --peer-auto-tls
      - --data-dir=/var/lib/etcd
  when: inventory_hostname in groups['master-2']

- name: start docker etcd container on master-3
  docker_container:
    name: etcd
    image: gcr.io/google_containers/etcd-amd64:3.0.17
    volumes:
    - '/etc/ssl/certs:/etc/ssl/certs'
    - '/var/lib/etcd-cluster:/var/lib/etcd'
    ports:
    - '4001:4001'
    - '2380:2380'
    - '2379:2379'
    restart_policy: always
    command:
      - etcd
      - --name=etcd2
      - --advertise-client-urls=http://{{ master3_ip }}:2379,http://{{ master3_ip }}:4001
      - --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      - --initial-advertise-peer-urls=http://{{ master3_ip }}:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster-token={{ ETCD_CLUSTER_TOKEN }}
      - --initial-cluster=etcd0=http://{{ master1_ip }}:2380,etcd1=http://{{ master2_ip }}:2380,etcd2=http://{{ master3_ip }}:2380
      - --initial-cluster-state=new
      - --auto-tls
      - --peer-auto-tls
      - --data-dir=/var/lib/etcd
  when: inventory_hostname in groups['master-3']

- pause: seconds=5
