###
# (C) Copyright (2012-2017) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- name: kubeadm init on master node
  shell: kubeadm init --apiserver-advertise-address={{ master1_ip }}

- name: update ~/.bashrc
  lineinfile:
    dest: ~/.bashrc
    line: export KUBECONFIG=/etc/kubernetes/admin.conf
    state: present

- shell: source ~/.bashrc

- pause: seconds=20

- name: install flannel networks addon
  shell: kubectl create -f /tmp/kubernetes/config/kube-flannel/

- pause: minutes=2

- name: make master be able to schedule pods
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-

- pause: seconds=5

#- name: install dashboard webUI addon
#  shell: kubectl create -f /tmp/kubernetes/config/kube-dashboard/
- shell: kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
- pause: minutes=1

- shell: kubectl proxy --address='0.0.0.0' &

- pause: seconds=10
#- name: check whether dashboard has come up
#  shell: curl -L http://{{ master1_ip }}:30000

- name: install heapster addon, the performance monitor addon
  shell: kubectl create -f /tmp/kubernetes/config/kube-heapster/influxdb/
- pause: seconds=10

- shell: kubectl create -f /tmp/kubernetes/config/kube-heapster/rbac/
- pause: seconds=10

- pause: minutes=2

- name: create user-defined cluster join token
  shell: kubeadm token create "{{ KUBERNETES_JOIN_TOKEN }}" --ttl 0

- name: save cluster data
  local_action: ini_file path=data/cluster_data.ini section=cluster_data option={{ item.name }} value={{ item.value }}
  with_items:
  - { name: 'CLUSTER_IP' , value: "{{ master1_ip }}" }
  - { name: 'CLUSTER_PORT' , value: '6443' }
  - { name: 'CLUSTER_TOKEN' , value: "{{ KUBERNETES_JOIN_TOKEN }}" }

- name: Print cluster data
  debug:
    msg:
    - " CLUSTER_IP = {{ master1_ip }} "
    - " CLUSTER_PORT = 6443 "
    - " CLUSTER_JOIN_TOKEN = {{ KUBERNETES_JOIN_TOKEN }}"
