###
# (C) Copyright (2012-2017) Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
###
---
- name: install git
  yum: name=git state=installed

- name: install pip 
  command: easy_install pip
  ignore_errors: true

- name: Check to see if pip is already installed.
  command: pip --version
  ignore_errors: true
  changed_when: false # read-only task
  check_mode: no
  no_log: True
  register: pip_is_installed

- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: pip_is_installed.rc != 0

- name: Install pip.
  shell: python /tmp/get-pip.py --proxy={{ http_proxy }}
  become: yes
  when: pip_is_installed.rc != 0

- name: Delete get-pip.py.
  file: state=absent path=/tmp/get-pip.py
  when: pip_is_installed.rc != 0

- name: install pip.
  pip: name=docker-py state=present

- name: create /tmp/kubernetes directory
  file: path=/tmp/kubernetes state=directory

- name: copy config files
  copy: src=config dest=/tmp/kubernetes

- name: Pull required docker images.
  docker_image: name={{ item }} state=present
  with_items:
  - gcr.io/google_containers/kube-proxy-amd64:v{{ KUBERNETES_VERSION }}
  - gcr.io/google_containers/kube-apiserver-amd64:v{{ KUBERNETES_VERSION }}
  - gcr.io/google_containers/kube-controller-manager-amd64:v{{ KUBERNETES_VERSION }}
  - gcr.io/google_containers/kube-scheduler-amd64:v{{ KUBERNETES_VERSION }}
  - quay.io/calico/kube-controllers:v2.0.0
  - quay.io/calico/node:v3.0.1
  - quay.io/calico/cni:v2.0.0
  - quay.io/coreos/flannel:v0.9.1-amd64
  - gcr.io/google_containers/heapster-amd64:v1.4.2
  - gcr.io/google_containers/heapster-grafana-amd64:v4.4.3
  - gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
  - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
  - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.7
  - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.7
